services:
  access-postgres:
    image: postgres:17-alpine
    container_name: ps-access-postgres
    environment:
      POSTGRES_DB: access_control
      POSTGRES_USER: platformuser
      POSTGRES_PASSWORD: Platform@2026
    ports:
      - "5450:5432"
    networks:
      - pisethjavaschool-dev-net
    volumes:
      - access-postgres-data:/var/lib/postgresql/data

volumes:
  access-postgres-data:
networks:
  pisethjavaschool-dev-net:
    external: true