spring:
  application:
    name: access-control-service
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5436}/${DB_NAME:platform_access_control}
    username: ${DB_USERNAME:restaurant-ktv-platform}
    password: ${DB_PASSWORD:Pisethjavaschool#2026}
  liquibase:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5436}/${DB_NAME:platform_access_control}
    user: ${DB_USERNAME:restaurant-ktv-platform}
    password: ${DB_PASSWORD:Pisethjavaschool#2026}
    change-log: classpath:db/changelog/db.changelog-master.yml
  
server:
  port: ${SERVER_PORT:8097}

logging:
  level:
    com.pisethjavaschool.accesscontrol: INFO
platform:
  clients:
    user:
      base-url: ${USER_SERVICE_URL:http://localhost:8089}
      root-path: /api/v1/users		
